### PR TITLE
Switch from pyup.io to Dependabot

### PR DESCRIPTION
**Pull request by stephendonner**
r? @davehunt @tarekziade

### CODE REVIEW

**Comment by ckolos** [comment]
Can I get some context on this switch? Our secops team has preferred pyup in the past

**Comment by davehunt** [comment]
> Can I get some context on this switch? Our secops team has preferred pyup in the past

pyup.io doesn't have full support for `Pipfile.lock`, so it will update a dependency without considering transient dependency version/platform restraints. As we're using pipenv and Pipfiles, Dependabot provides a more robust and complete solution.

**Comment by ckolos** [comment]
I checked with secops and they have no issue with this change, but respectfully ask if you would also do as described here: https://pipenv.readthedocs.io/en/latest/advanced/#generating-a-requirements-txt

**Comment by stephendonner** [comment]
@ckolos I don't have a problem with that request, sure.

Questions:

1) can you point to an example where this is done for a Mozilla project?  Just trying to get a sense of the workflow
2) do you want the resulting requirements.txt in-tree?
3) generated _before_ merge time of PRs, such as these, which change requirements/dependencies, and then checked it alongside the Pipfile/Pipfile.lock?

Thanks again!

**Comment by davehunt** [comment]
I'm curious why this is being asked for? We're not using a requirements.txt, so what purpose would this fulfil? Also, as pipenv does not include hashes in generated requirements files, the resulting requirements file would be less secure than the Pipfile.lock, which includes all hashes.

**Comment by ckolos** [comment]
```
We haven't updated the checklist, but socorro and tecken are testing out disabling the pyup bot and switching to Renovate or Dependabot. Those bots are smarter about updating PRs and making new ones.

Sec-wise Dependabot is preferable for this feature: https://dependabot.com/blog/automatically-respond-to-security-advisories/

Secops will run the pyup CLI tool in a jenkins security job and surface any relevant warnings. For that job and to have github's sec. alerts, it would be handy if they could sync and check in the requirements file: https://pipenv.readthedocs.io/en/latest/advanced/#generating-a-requirements-txt
```

This is what I've been told when asking about enabling this over pyup. Feel free to discuss with secops should you have any objections.

**Pull request merged**
